### ISSUE TITLE
IR Rotatron MK2 wrong direction after time warp

### ISSUE THREAD

**Issue by CMXLargo** [MagicSmokeIndustries/InfernalRobotics#140]
After a timewarp rotatron turns in wrong direction. See my video.

[https://www.youtube.com/watch?v=Cgnj45xc5Ak](url)

InfernalRobotics 2.0.10
KSP 1.2.2

**Comment by ZiwKerman** [comment]
Interesting. Can you post the craft file as well, so I can test it, please?

Sent from my iPad

On 19 Dec 2016, at 22:10, CMXLargo <notifications@github.com> wrote:

After a timewarp rotatron turns in wrong direction. See my video.

https://www.youtube.com/watch?v=Cgnj45xc5Ak <url>

InfernalRobotics 2.0.10
KSP 1.2.2

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/MagicSmokeIndustries/InfernalRobotics/issues/140>, or mute
the thread

**Comment by CMXLargo** [comment]
Only with OPT 1.9.2 Parts.... please

[Prototype.zip](https://github.com/MagicSmokeIndustries/InfernalRobotics/files/662326/Prototype.zip)

**Comment by ZiwKerman** [comment]
Can you try replacing your current InfernalRobotics.dll with this one:
https://drive.google.com/open?id=0B9f5PHcywXQIQXJ0RHdaZWJQQWM

It is a minor change, but it solves couple issues. Also with this dll I could not reproduce your problem.

**Comment by CMXLargo** [comment]
The problem still exists. But it is only present when the rotor is not in the zero position during the time warp. Have you tested it with my Craft-File?

**Comment by ZiwKerman** [comment]
I did, though not extensively. Will do more tests tomorrow.

**Comment by CMXLargo** [comment]
I've found the problem is not the rotor, but the angle of the rotor base is changing. The IR Rotatron MK2 has an arrow or nose that change position abruptly.

**Comment by ZiwKerman** [comment]
Did you try the dll I posted, it should fix the rotating base issue with timewarp.

**Comment by CMXLargo** [comment]
I replaced the DLL with yours. Problem still exists. I think that after the Timewarp the base to the last rotor position is set to zero. Thus, although the rotor is still the base at the adjusted angle, the base is rotated as if the rotor were in the zero position. If you want I can make you again a video in which you can see it exactly.

**Comment by CMXLargo** [comment]
I tested again today. The problem is solved with the new DLL. No idea why the error was active again this week.
